---
title: "Compiling Advanced R"
author: "Simiao Gao"
date: "9/7/2020"
output: pdf_document
---


Reference: https://brettklamer.com/diversions/statistical/compile-hadleys-advanced-r-programming-to-a-pdf/

## Error1
Error: Failed to install 'advr' from GitHub: \newline
  Failed to install 'rlang' from GitHub: \newline
  Could not find tools necessary to compile a package \newline

Solution: the tool is automatically installed. After installing, rerun the code.

## Error2

Error: .onLoad failed in loadNamespace() for 'pkgload', details: \newline
  call: loadNamespace(name) \newline
  error: there is no package called ‘desc’ \newline

Solution: install package ‘desc’.

## Error3
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : \newline
  there is no package called ‘sessioninfo’ \newline

Solution: install package ‘sessioninfo’.

## Error4
Error in loadNamespace(name) : there is no package called ‘bookdown’  \newline

Solution: install package ‘bookdown’.

## Error5

Quitting from lines 80-81 (Names-values.Rmd) \newline
Error in library(lobstr) : there is no package called 'lobstr' \newline
Calls: local ... withCallingHandlers -> withVisible -> eval -> eval -> library \newline

Solution: install package ‘lobstr’.

## Error6

Quitting from lines 535-550 (R6.Rmd)  \newline
Error in (function (cond)  :  \newline
  error in evaluating the argument 'drv' in selecting a method for function 'dbConnect': there is no package called 'RSQLite' \newline
  
Solution: install package ‘RSQLite’.

## Error7
Quitting from lines 38-40 (Perf-measure.Rmd)  \newline
Error in library(profvis) : there is no package called 'profvis' \newline

Solution: install package ‘profvis’.

## Error8
Quitting from lines 38-40 (Perf-measure.Rmd) \newline
Error in library(bench) : there is no package called 'bench' \newline

Solution: install package ‘bench’.

## Error8
Quitting from lines 233-234 (Perf-measure.Rmd)  \newline
Error: `ggbeeswarm` must be installed to use `type = "beeswarm"` option. \newline

Solution: install package ‘ggbeeswarm’.

## Error9
! fontspec error: "font-not-found" \newline
!  \newline
! The font "Inconsolata" cannot be found. \newline

Solution: install package ‘extrafont’. Download "Inconsolata" from Google Font and put the font file in the font library.

## Error10
! LaTeX Error: Environment sidebar undefined. \newline

Error: LaTeX failed to compile _main.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See _main.log for more info. \newline

Solution: install tinytex. 

